### PR TITLE
Version 1.3.0

### PR DESCRIPTION
**Pull request by Sandertv**
This pull requests adds features for version 1.3.0. A lot of new translations are required, most of them are simply one word translations.

@jerryzooyoyo: Could you update the Chinese translations please?
@MrKiaN: Could you update the Persian translations please?

All to-be-translated words and sentences can be found in the English file. I pre-made most of it, just the translations are to-do. Thanks a lot in advance! 😄

### CODE REVIEW

**Comment by Sandertv** [comment]
@HimbeersaftLP 
@jerryzooyoyo 
@MrKiaN 
@opkiler22789 
Ping!

**Comment by HimbeersaftLP** [comment]
Pong!

**Comment by Sandertv** [comment]
😄

**Comment by opkiler22789** [comment]
Pong)

**Comment by NycuRO** [comment]
@Sandertv I can help with translation of Romanian language?

**Comment by Sandertv** [comment]
@NycuRO Please! :) You can copy the english translation and trandlate the nodes :)

**Comment by NycuRO** [comment]
@Sandertv Ready

**Comment by Sandertv** [comment]
Merging time!

**Pull request merged**
