### PR TITLE
Implemented /deselect command

### PR DESCRIPTION
**Pull request by matcracker**
This command allows to clear the selection in use.

### CODE REVIEW

**Comment by Sandertv** [comment]
Is there any particular use case for this?

**Comment by matcracker** [comment]
Well, currently I'm hooking BS to BedcoreProtect to rollback some selected areas. It could happens to forgot to select a new one area and the player continues to rollback the old one but implementing Selection::clear() and, why not, in some cases a useful command that resolves the problem.

**Comment by matcracker** [comment]
Obviously I think it is useful also in other cases. I often forget that I had previously selected an area but with the command I would be on the safe side.

**Comment by Sandertv** [comment]
Fair enough! The 3.x line is on a feature freeze though, so I'd prefer if this could go to the 4.0.0 branch. Would you mind doing that.

**Comment by matcracker** [comment]
Sure, I'll do that.

**Pull request closed without merging**
