### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
You really should recommend that they compile using DevTools and not a zip to phar converter...

http://pmt.mcpe.me is down.

### CODE REVIEW

**Comment by Sandertv** [comment]
I'm going to remove this on the 1.4.0 branch anyways, because it has a submodule which won't be included if you download the ZIP. Mind if I close this?

**Comment by Sandertv** [comment]
I'm too lazy to resolve merge issues :P

**Comment by SOF3** [comment]
Simply link to Poggit :)

**Comment by Sandertv** [comment]
Yep, I will.

**Pull request closed without merging**
